import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthSessionProviders from "@/providers/NextAuthSessionProviders";
import ToastProviders from "@/providers/ToastProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProviders />
        <NextAuthSessionProviders>{children}</NextAuthSessionProviders>
      </body>
    </html>
  );
}
